services:
  web:
    build: ./web
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      Services:AiServiceUrl: http://ai:7000
      Services:DatabaseUrl: mongodb://db:27017
  ai:
    build: ./ai
    stop_signal: SIGINT
    environment:
      DatabaseUrl: mongodb://db:27017
    volumes:
      - ./ai/db:/run/db:rw
      - ./ai/resources:/run/resources:ro
  db:
    image: mongo:8.0.0-rc13-jammy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
volumes:
  mongo_data:
    driver: local
