name: ai_env
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - pip
  - python==3.10
  - pytorch==2.8.0
  - torchaudio==2.8.0
  - torchvision==0.23.0
  - pytorch-cuda=12.4
  - flask==3.1.2
  - pypdf==6.1.1
  - colorama==0.4.6
  - waitress==3.0.2
  - chromadb==0.5.0
  - Werkzeug==3.1.3
  - requests==2.32.5
  - langchain==0.3.27
  - beautifulsoup4==4.14.0
  - langchain-core==0.3.76
  - langchain-chroma==0.2.6
  - langchain-community==0.3.30
  - langchain-huggingface==0.3.1
  - sentence-transformers==5.1.1
  - cryptography==46.0.1
  - conda-forge::transformers==4.56.2
  - conda-forge::sentence-transformers==3.0.1
  - conda-forge::pymongo=4.15.1
  - conda-forge::dacite=1.9.2
  - pip:
      - ollama==0.6.0
      - huggingface-hub==0.35.1